{
 "title": "New dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "initerval",
    "label": "initerval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "rtorrent_download_total_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(rtorrent_download_total_bytes{}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "rtorrent_upload_total_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(rtorrent_upload_total_bytes{}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "qbittorrent_download_total_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(qbittorrent_download_total_bytes{}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "qbittorrent_upload_total_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(qbittorrent_upload_total_bytes{}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "transmission_download_session_bytes ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(transmission_download_session_bytes{}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "transmission_upload_session_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(transmission_upload_session_bytes{}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}